import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import ProductService from '../api/product-service';

const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

//export async function getServerSideProps() { getStaticProps
export async function getStaticProps() {
  const data = await ProductService.getTable();

  return {
    props: {
      people: data.people,
      titles: data.titles
    },
    revalidate: 60
  };
}

export default function Home({ people, titles }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {people.map((person, index) => {
          return (
            <Link key={index}
              href={`/${index}`}
            >
              <a style={{ margin: 10, padding: 7, border: "2px solid black" }}>{person.map((prop, index) => prop ? `${titles[index]}: ${prop}. ` : null)}</a>
            </Link>
          )
        })}
      </main>
    </div >
  )
}
